import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ImagePlus,X,WandSparkles,Loader2,Languages,Moon,History,Trash2,CheckCircle2,RotateCcw,ShieldCheck,Sparkles} from 'lucide-react';
import {createWorker} from 'tesseract.js';
import './styles.css';

const KEY='fahhemni-history-v2';
const examples=['حل المعادلة: 2x + 5 = 17','إذا كان محيط مربع 36 سم، فما طول ضلعه ومساحته؟','احسب: (3 + 5) × 4 − 6'];
function App(){
 const [lang,setLang]=useState('ar'),[text,setText]=useState(''),[image,setImage]=useState(null),[url,setUrl]=useState(''),[ocr,setOcr]=useState(''),[loading,setLoading]=useState(false),[stage,setStage]=useState('input'),[result,setResult]=useState(null);
 const [history,setHistory]=useState(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}); const fileRef=useRef();
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(history.slice(0,20))),[history]);
 const t={ar:{sub:'صوّر الوثيقة أو اكتب المسألة، وخذ شرحًا واضحًا خطوة بخطوة.',drop:'اضغط لاختيار صورة أو اسحبها هنا',manual:'أو اكتب المسألة يدويًا',an:'حلّل وفسّر'},fr:{sub:'Photographiez le document ou écrivez le problème pour une explication étape par étape.',drop:'Touchez pour choisir une image',manual:'Ou écrivez le problème',an:'Analyser'},en:{sub:'Upload a document or type a problem and get a clear step-by-step explanation.',drop:'Tap to choose an image',manual:'Or type the problem',an:'Analyze & explain'}}[lang];
 function choose(f){if(!f?.type.startsWith('image/'))return;setImage(f);setUrl(URL.createObjectURL(f));setOcr('');setResult(null);setStage('input')}
 async function analyze(){if(!text.trim()&&!image)return;setLoading(true);setStage('analysis');let s=text.trim();if(!s&&image){try{const w=await createWorker('ara+fra+eng');const r=await w.recognize(image);s=r.data.text||'';setOcr(s);await w.terminate()}catch{}}let r=null;try{const q=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:s,language:lang})});if(q.ok)r=await q.json()}catch{}r=r||local(s);setResult(r);setStage('result');setHistory(h=>[{id:Date.now(),title:r.title,input:s||'صورة وثيقة',date:new Date().toLocaleString('ar-MA')},...h].slice(0,20));setLoading(false)}
 function reset(){setText('');setImage(null);setUrl('');setOcr('');setResult(null);setStage('input')}
 return <div className="app"><header><div className="brand"><b>ف</b><strong>فهمني</strong></div><div className="actions"><button onClick={()=>setLang(lang==='ar'?'fr':lang==='fr'?'en':'ar')}><Languages size={16}/>{lang.toUpperCase()}</button><button onClick={()=>document.documentElement.classList.toggle('light')}><Moon size={16}/></button></div></header>
 <main><section className="hero"><div className="pill"><Sparkles size={14}/> مساعد تعليمي ذكي</div><h1>صوّر الوثيقة<br/>ونخبرك <span>ماذا تفعل.</span></h1><p>{t.sub}</p></section>
 <div className="steps"><i className={stage==='input'?'on':''}>01 · المسألة</i><i className={stage==='analysis'?'on':''}>02 · التحليل</i><i className={stage==='result'?'on':''}>03 · الشرح والنتيجة</i></div>
 {stage!=='result'?<section className="card"><div className="drop" onClick={()=>fileRef.current.click()}>{url?<><img src={url}/><button className="remove" onClick={e=>{e.stopPropagation();setImage(null);setUrl('')}}><X/></button></>:<><div className="upload"><ImagePlus/></div><b>{t.drop}</b><small>JPG, PNG — حتى 10MB</small></>}</div><input hidden ref={fileRef} type="file" accept="image/*" onChange={e=>choose(e.target.files?.[0])}/><div className="or">أو</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={t.manual+'…'}/><div className="examples">{examples.map(x=><button key={x} onClick={()=>setText(x)}>{x}</button>)}</div><button className="primary" disabled={loading||(!text.trim()&&!image)} onClick={analyze}>{loading?<><Loader2 className="spin"/> جاري التحليل…</>:<><WandSparkles/> {t.an}</>}</button><div className="privacy"><ShieldCheck size={15}/> الصور لا تُحفظ على الخادم في هذه النسخة.</div></section>:<Result result={result} reset={reset}/>} 
 {ocr&&stage!=='result'&&<section className="card"><b>النص المستخرج</b><textarea value={ocr} onChange={e=>setOcr(e.target.value)}/></section>}
 <section className="card history"><div className="title"><History size={18}/> السجل <span>{history.length}</span></div>{history.length?<>{history.slice(0,5).map(x=><div className="hi" key={x.id}><div><b>{x.title}</b><small>{x.input.slice(0,80)}</small></div><small>{x.date}</small></div>)}<button className="clear" onClick={()=>setHistory([])}><Trash2 size={15}/> مسح السجل</button></>:<small className="muted">ستظهر هنا المسائل التي حللتها.</small>}</section></main><footer>فهمني © 2026 — افهم، حلّل، تعلّم.</footer></div>}
function Result({result,reset}){return <section className="card result"><div className="rh"><div><small>نتيجة التحليل</small><h2>{result?.title}</h2></div><span><CheckCircle2 size={16}/> تم التحليل</span></div><div className="summary">{result?.summary}</div>{result?.steps?.map((s,i)=><div className="sol" key={i}><b>{i+1}</b><p>{s}</p></div>)}<div className="answer"><small>الإجابة النهائية</small><strong>{result?.answer}</strong></div>{result?.note&&<div className="note">⚠️ {result.note}</div>}<button className="primary" onClick={reset}><RotateCcw/> مسألة جديدة</button></section>}
function local(s){let m=s.replace(/[−–]/g,'-').match(/([+-]?\d+(?:\.\d+)?)\s*x\s*([+-]\s*\d+(?:\.\d+)?)?\s*=\s*([+-]?\d+(?:\.\d+)?)/i);if(m){let a=+m[1],b=m[2]?+m[2].replace(/\s/g,''):0,c=+m[3],x=(c-b)/a;return{title:'حل معادلة خطية',summary:'معادلة خطية بمجهول واحد. نعزل x تدريجيًا ثم نتحقق بالتعويض.',steps:[`نكتب المعادلة: ${a}x ${b>=0?'+ '+b:'- '+Math.abs(b)} = ${c}.`,`ننقل الحد الثابت: ${a}x = ${c-b}.`,`نقسم الطرفين على ${a}.`,`نتحقق بالتعويض في المعادلة الأصلية.`],answer:`x = ${Number.isInteger(x)?x:x.toFixed(4)}`,note:'نتيجة رياضية آلية.'}}
 let a=s.replace(/احسب|calculate|=/gi,'').replace(/×/g,'*').replace(/÷/g,'/').trim();if(/^[\d\s+\-*/().]+$/.test(a)&&/[+\-*/]/.test(a)){try{let v=Function('return '+a)();if(Number.isFinite(v))return{title:'حساب عددي',summary:'تم التعرف على تعبير حسابي بسيط.',steps:['نرتب العمليات حسب الأولوية.','نحسب التعبير.','نراجع النتيجة.'],answer:String(v),note:'نتيجة حسابية آلية.'}}catch{}}
 let q=s.match(/محيط\s+مربع\s+(\d+(?:\.\d+)?)/i);if(q){let p=+q[1],side=p/4,area=side*side;return{title:'مسألة هندسية — مربع',summary:'من المحيط نستخرج طول الضلع ثم نحسب المساحة.',steps:['المحيط = 4 × الضلع.',`الضلع = ${p} ÷ 4 = ${side}.`,`المساحة = الضلع × الضلع = ${area}.`],answer:`الضلع = ${side}، المساحة = ${area}`,note:'نتيجة هندسية آلية.'}}
 return{title:/طلب|إجراء|إداري|administratif/i.test(s)?'إشعار / طلب إداري':'تحليل الوثيقة',summary:'تمت قراءة النص، وهذه نسخة تعمل محليًا. لرفع مستوى فهم الوثائق والسياق، اربط مفتاح نموذج الذكاء الاصطناعي في Vercel.',steps:['استخراج النص من الصورة أو الإدخال اليدوي.','تحديد نوع المحتوى بشكل أولي.','تحليل المطلوب وتحديد الخطوة التالية.'],answer:'جاهز للتحليل المتقدم',note:'لا تعتمد على النتيجة وحدها في القرارات القانونية أو المالية أو الصحية.'}}
createRoot(document.getElementById('root')).render(<App/>);
